### ISSUE TITLE
"race condition where mkfs.ext4 sees the fat32 partition again"

### ISSUE THREAD

**Issue by declanmalone** [tomuta/debian-mini-odroid-c1#1]
Just a thought on this. It's likely that if you run partprobe (from the parted package) before the mkfs and mount commands, the problem goes away.

**Comment by tomuta** [comment]
Thanks for the hint, I'll look into it!
Thomas

```
  From: declanmalone <notifications@github.com>
```

 To: tomuta/debian-mini-odroid-c1 debian-mini-odroid-c1@noreply.github.com 
 Sent: Sunday, January 4, 2015 2:50 PM
 Subject: [debian-mini-odroid-c1] "race condition where mkfs.ext4 sees the fat32 partition again" (#1)

Just a thought on this. It's likely that if you run partprobe (from the parted package) before the mkfs and mount commands, the problem goes away.—

**Comment by tomuta** [comment]
Looks like that fixes it indeed, although I have only tested it with a few builds so far.  But I haven't run into it.
