### ISSUE TITLE
How to include wifi support

### ISSUE THREAD

**Issue by vallettea** [tomuta/debian-mini-odroid-c1#18]
Hello, thanks for this image, works perfectly.

I would like to know if you have some experience with installing drivers for wifi dongles as for the moment, none of them are recognized with this debian ?

**Comment by r120a** [comment]
I have used this image with realtek and atheros based wifi dongles.  In my circumstance, I needed to add the following packages.

wpasupplicant
firmware-realtek (for Realtek based devices)
firmware-atheros (for Atheros based devices)

I then configured the /etc/network/interfaces file appropriately and it worked.

**Comment by tomuta** [comment]
Yeah, I don't really like to have these things pre-installed on the image itself, as there is no wifi built in.  However, that's the whole point of my project, you should be able to easily customize the build scripts to generate images that support this and have these packages pre-installed and pre-configured :-)

**Comment by vallettea** [comment]
cool, i'm trying at the moment
