### ISSUE TITLE
Black screen (hdmi)

### ISSUE THREAD

**Issue by kevincaradant** [tomuta/debian-mini-odroid-c1#21]
Hi, 
 i don't understand , i'm trying for four hours but without success :(.

I built and created the image and then copy on the SD card with the command "dd" on linux.

But when i start the odroid. I have the red light and blue light ( blink) with the ethernet ( blink ) but my screen is black or grey when i change the resolution in boot.ini. But never blank line on the screen :(.

Have you a idea of the problem ?
( i tried ubuntu 14.04 LTS and if i configure the resolution of the screen in boot.ini , that works, btw, it's the only which works  )

Thanks you :)

Exemple of the boot.ini whick works with ubuntu 14.04 : 

ODROIDC-UBOOT-CONFIG

// Possible screen resolutions
// Uncomment only a single Line! The line with setenv written.
// At least one mode must be selected.

// setenv m "vga"           # 640x480
// setenv m "480p"          # 720x480
// setenv m "576p"          # 720x576
// setenv m "800x480p60hz"  # 800x480
// setenv m "800x600p60hz"  # 800x600
// setenv m "1024x600p60hz" # 1024x600
  setenv m "1024x768p60hz"  # 1024x768
// setenv m "1360x768p60hz"     # 1360x768
// setenv m "1366x768p60hz" # 1366x768
// setenv m "1440x900p60hz" # 1440x900
// setenv m "1600x900p60hz" # 1600x900
// setenv m "1680x1050p60hz"    # 1680x1050
// setenv m "720p"          # 720p 1280x720
// setenv m "800p"          # 1280x800
// setenv m "sxga"          # 1280x1024
// setenv m "1080i50hz"          # 1080I@50Hz
// setenv m "1080p24hz"          # 1080P@24Hz
// setenv m "1080p50hz"          # 1080P@50Hz
// setenv m "1080p"                # 1080P@60Hz
// setenv m "1920x1200"     # 1920x1200

// HDMI DVI Mode Configuration
setenv vout_mode "hdmi"
// setenv vout_mode "dvi"

// HDMI BPP Mode
setenv m_bpp "32"
// setenv m_bpp "24"
// setenv m_bpp "16"

// UHS Card Configuration
// Uncomment the line below to **DISABLE** UHS-1 MicroSD support
// This might break boot for some brand models of cards.
// setenv disableuhs "disableuhs"

// Disable VPU (Video decoding engine, Saves RAM!!!)
// 0 = disabled
// 1 = enabled
setenv vpu "1"

// Disable HDMI Output (Again, saves ram!)
// 0 = disabled
// 1 = enabled
setenv hdmioutput "1"

// Default Console Device Setting
// setenv condev "console=ttyS0,115200n8"        # on serial port
setenv condev "console=tty0"                    # on display (HDMI)
// setenv condev "console=ttyS0,115200n8 console=tty0"   # on both

// Boot Arguments
setenv bootargs "root=UUID=e139ce78-9841-40fe-8823-96a304a09859 rootwait ro ${condev} no_console_suspend vdaccfg=0xa000 logo=osd1,loaded,0x7900000,720p,full dmfc=3 cvbsmode=576cvbs hdmimode=${m} m_bpp=${m_bpp} vout=${vout_mode} ${disableuhs}"

// Booting
fatload mmc 0:1 0x21000000 uImage
fatload mmc 0:1 0x22000000 uInitrd
fatload mmc 0:1 0x21800000 meson8b_odroidc.dtb
fdt addr 21800000

if test "${vpu}" = "0"; then fdt rm /mesonstream; fdt rm /vdec; fdt rm /ppmgr; fi

if test "${hdmioutput}" = "0"; then fdt rm /mesonfb; fi

bootm 0x21000000 0x22000000 0x21800000"

**Comment by kevincaradant** [comment]
OK , my bad , i'm working on the problem for many hours but now i do a refresh on the page and i'm seeing "update with jessie from 4 hours", exactly the same moment where i loaded this page x). and that works your update . Timing perfect :p.. Thx a lot. I close this thread.

**Comment by tomuta** [comment]
I'm glad you got it figured out :-)

**Comment by kevincaradant** [comment]
Yes :) but just,  i need a précision on this debian.  I m trying to install xbmc but I  have a problem with gtk.  Gtk can not opened display,  something like that.  Is it à problem with debian and the gpu which is inactif or its totally à other problem ?  Thanks :).  Again 3 hours without success :/
