### ISSUE TITLE
/boot/system.map read only filesystem

### ISSUE THREAD

**Issue by kevincaradant** [tomuta/debian-mini-odroid-c1#22]
Hi ,

is it normal that /boot/system.map is in read file system only. I can't install the new image of linux ? Have  you a idea ? :)

PS : i have used this to update the kernel : https://github.com/mdrjr/odroid-utility

Thank you for your help

**Comment by kevincaradant** [comment]
so i found a solution for that. I edit the /etc/fstab to get /boot with rw permissions. OK now an other problem.

when i'm trying to update the kernel with :  https://github.com/mdrjr/odroid-utility
i have this error : 

![screenshot_2015-05-19-16-07-50](https://cloud.githubusercontent.com/assets/6093175/7704913/718374de-fe41-11e4-9384-3a76b2514a78.png)

So tell me that you know what i have to do :) because i'm lost

**Comment by phipolis** [comment]
Don't know if you ever worked around this, but as referenced [here](http://forum.odroid.com/viewtopic.php?f=114&t=8084&start=100#p114044), the file `/boot/meson8b_odroidc.dtb` is both a part of a debian package and outside of it created by this installer. if you rename it, the install will succeed and replace it. At that point, you can delete the renamed file.
