### ISSUE TITLE
Compilation errors observed after enabling profiling options 

### ISSUE THREAD

**Issue by MaheshWaidande** [tomuta/debian-mini-odroid-c1#30]
Hi All 

I am working on building/porting Julia on ppc64le architecture. I am using Ubuntu 14.10 on top of ppc64le hardware, while compiling Julia code (master branch) I was getting segmentation fault, I am able to resolve this segmentation fault by turning on ‘MEMDEBUG’ flag from ‘src/options.h’ file.  

I decided to work more this issue and try to find out root cause of segmentation fault, so I started studying/understanding memory management scheme of Julia. 

To understanding GC and de-allocation mechanism I turn on profiling options ‘MEMPROFILE’ ,’ GC_TIME’  from ‘options.h’  file (by default they are commented out I uncomment those) but when I try to compile code with these profiling flags on julia compilation (make debug) gets failed.  

Below compilation errors I observed after enabling, 
1. ‘GC_TIME’ flag 
     gc.c:237:26: error: current_heap undeclared (first use in this function)
     #define HEAP(x) (*((void)current_heap,&(x)))
1. ‘MEMPROFILE’ flag 
   gc.c:2414:21: error: pool_t has no member named pages

My Machine details are: 
Linux 3.16.0-30-generic #40-Ubuntu SMP ppc64le ppc64le ppc64le GNU/Linux 

-Mahesh

**Comment by tomuta** [comment]
Are you sure this is about the debian-mini-odroid-c1 project?  Any chance you meant to create this issue for another github project?

**Comment by MaheshWaidande** [comment]
I am extremely sorry, this is my fault. Actually issue I raised is not for this community, it’s for some other project. Please ignore it I by mistaken post question on this community.

**Comment by tomuta** [comment]
That's ok, no worries ;-)
