### ISSUE TITLE
Will not generate ssh host key on jessie

### ISSUE THREAD

**Issue by Rotonen** [tomuta/debian-mini-odroid-c1#6]
How to reproduce: simply substitute "stable" with "jessie" in common.mk.

Since Debian jessie is using systemd per default, the patch for the SysV init file will not get executed on the first boot due to there being a distro provided valid systemd setup. Jessie will be under the keyword 'stable' soon and thus break this script.

Alternatives:

1) Make a systemd-tolerant solution for the first-boot ssh host key generation
2) Pin the script release in common.mk wheezy (it will be maintained oldstable for a year when jessie comes out)
3) Make debootstrap use SysV Init

**Comment by tomuta** [comment]
As I am not familiar with systemd, do you happen to have a patch?  I'd be more than happy to integrate support for it.

**Comment by Rotonen** [comment]
http://wiki.prgmr.com/mediawiki/index.php/Debootstrap

Looking around, rc.local should still work and the approach in that wiki seems to do the job.

Jessie has a systemd service in place for executing /etc/rc.local if it exists and is executable

```
/lib/systemd/system/rc-local.service
```

**Comment by Rotonen** [comment]
I'll make a pull request on this later today. The scope has slightly extended due to jessie sshd default configuration also disallowing password-based root logins.

**Comment by Rotonen** [comment]
Pull request:

https://github.com/tomuta/debian-mini-odroid-c1/pull/8

Jessie-as-upstream-means support as a whole will be an another issue.

**Comment by tomuta** [comment]
Thanks for your work!  I'm hoping to have some time this week to look at your pull requests!

**Comment by tomuta** [comment]
I will close this issue for now, see my comment in your pull request.
